### ISSUE TITLE
Improve Developer Experience with Arc

### ISSUE THREAD

**Issue by PatrickHeneise** [arc-repos/architect#274]
I'm migrating a project from Google Cloud Functions to AWS with Arc. So far I'm quite happy with the results and arc makes it fairly easy to deploy to Lambda, thanks for that!

One thing I quite liked in GCF was structure of functions:

```
index.js
- functions/
- functions/eventsList.js
- functions/eventsGet.js
- functions/eventsNew.js
...
```

`index.js` looks like

```
const cors = require('./lib/middlewares/cors')
const handleErrors = require('./lib/middlewares/handleErrors')
const getId = require('./lib/getId')

exports.models = handleErrors(
  cors((request, response) => {
    switch (request.method) {
      case 'GET': {
        if (getId(request.path)) {
          return require('./functions/eventsGet')(request, response)
        }
        return require('./functions/eventsList')(request, response)
      }
      case 'POST': {
        return require('./functions/eventsNew')(request, response)
      }
    }
  })
)
```

This allows to group functions by "business case"/unit and it's easy to navigate to each file with shortcuts. Libraries and helpers can be included in several individual functions while they're available to the whole unit. They don't need to be copied into each function folder and refresh instantly (unlike shared code in arc).

I feel like this could greatly improve the developer experience to bundle the code and have more control over the entrypoint, rather than having so many individual folders with an `index.js`.

**Comment by brianleroux** [comment]
I'm closing this out for now because I can't think of a clean way to get this sort of experience without falling into either having 1 big function for everything (and using routing logic), adding new configuration which has bad tradeoffs for ppl that like moving stuff around, or building a compile chain (something we're not opposed to…but not ready for just yet). 

Please feel free to reopen or add new ideas! Def want to improve our perceived dev experience.
