### ISSUE TITLE
CORS: support for preflighted requests

### ISSUE THREAD

**Issue by alexdilley** [arc-repos/architect#285]
Where frontend and backend do not reside at the same origin (`www.example.com` vs `api.example.com`), preflighted requests are commonly an unavoidable necessity: any request with `Content-Type: application/json`, for example, will trigger an `OPTIONS` request. Supplying credentials by cookie adds a further level of complication over this scheme (i.e. specific-url `Access-Control-Allow-Origin` only). Currently `OPTIONS` methods need to be added by hand in AWS Console; two headers drive the main configuration: `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials` – API Gateway derives the appropriate set of `Access-Control-Allow-Methods` by those defined on the resource.

Proposal to support either a blanket generation of an `OPTIONS`-method-per-resource, just to those resources defining non-`GET` endpoints, or only to those where explicitly stated, taking a base form possibly similar to:

```
@cors
example.com

@domain
api.example.com
```

Considerations:

- [ ] per-environment values (staging vs production)
- [ ] with/without credentials (cookies vs tokens for auth)
- [ ] if token-based auth, support for wildcard `Allow-Origin`
- [ ] removal of `SameSite` option in cookie generation

Demo of common flow in action: [alexdilley/cors-blimey](https://github.com/alexdilley/cors-blimey).

Discussion and implementation of solution on AWS SAM: awslabs/serverless-application-model#464 (currently @ `develop`).

**Comment by alexdilley** [comment]
Serverless Framework released their support for multi-origin CORS configuration just now. I've a demo of its usage [here](https://github.com/alexdilley/sls-cors) should there be a desire to implement something similar in arc.

**Comment by ryanblock** [comment]
With all the changes we've made for hosting same-origin apps over the last couple month, it seems like this may not be as strong of a necessity. If you think that's not the case, please feel free to keep this issue going, shoot a PR, tell me to get lost, etc.
🌈

**Comment by eshikerya** [comment]
@ruanblock, is there any possibility to bring this (CORS) to arc? it is really required to get access from mobile device to API implemented with arc. should I consider another solution for api implementation?

**Comment by ryanblock** [comment]
@eshikerya there's a lot going on in CORS, so we'll need to narrow this request/comment down.

Here's specifically what we currently support if you set `cors: true` in an `arc.http()` response, to help us get started: https://github.com/architect/functions/blob/master/src/http/http.js#L156

Per our feature request template, can you please provide:
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (Example: I find it frustrating when trying to _____ because _____...)

**Describe the solution you'd like**
A clear and concise description of what you'd like to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. These are quite helpful! (Example: If it did _____ instead of _____, users would still have problems because _____...)

**Additional context or notes**
Add any other context or screenshots about the feature request here.

Use cases and implementation details are also helpful.

**Comment by eshikerya** [comment]
@ryanblock I got it solved with arc@6
```cors: true``` doesn't work, cause browser make ```OPTIONS``` request as preflight to know is it allowed to make POST/PATCH/DELETE to required domain. and current api configuration will not proxy the request to the script. and this is the main issue.
accidentally I discovered: all requests which doesn't follow described in API Gateway will end up in get-index, which is required for arc@6, so my solutions was dead simple:
```javascript
// file: src/http/get-index/index.ts
export const handler = async (req) => {
    if (req.httpMethod == 'OPTIONS') {
        // compare to allowed origins, if it exists, then return origin, if not - return false
        const origin = checkOrigin(req); 
        if (origin === false) {
            return {statusCode: 403}
        } else {
            return {
                statusCode: 200,
                headers: {
                    'Access-Control-Allow-Origin': origin,
                    'Access-Control-Allow-Methods': 'POST, OPTIONS',
                    'Access-Control-Allow-Headers': 'Content-Type',
                    'Access-Control-Max-Age': 86400,
                },
            };
        }
    } else {
        return {statusCode: 503};
    }
};
```

**Comment by saifalfalah** [comment]
@eshikerya's solution worked for me too.

For preflight requests the request got routed to get-index where I set the required CORS headers.
