### ISSUE TITLE
Cannot deploy only to staging

### ISSUE THREAD

**Issue by mrnagydavid** [arc-repos/architect#338]
First: You got a really cool thing going here!

**Describe the bug**
I have set up a simple repo following the tutorial in the medium article.
I noticed that it deploys every time to both staging and production.
`npx deploy`
`npx deploy staging`
`ARC_DEPLOY=staging npx deploy`
All of the above result in deploying to both staging and production:
```
Found new resources to create! Creating them now...
https://dkpp1htype.execute-api.eu-central-1.amazonaws.com/staging
https://p09cp5knu0.execute-api.eu-central-1.amazonaws.com/production
```

**To Reproduce**
```
mkdir testapp
cd testapp
npm init --yes
npm i @architect/architect
```
Create `.arc:`
```
@app
testapp

@aws
region eu-central-1
profile amazon-profile

@http
get /
```

`npx create local`

Make sure that `echo $ARC_DEPLOY` is empty.

And finally any of the following commands:
`npx deploy`
`npx deploy staging`
`ARC_DEPLOY=staging npx deploy`

**Expected behavior**
Based on https://arc.codes/reference/arc-deploy, the expected behaviour is:
`Deploys code in /src to staging. If ARC_DEPLOY=production is set, the code in /src will be deployed to production.`

**Desktop (please complete the following information):**
- "@architect/architect": "^5.5.10"

I wonder if it is a bug (probably too serious to go unnoticed and I haven't found any tickets) or just me making a mistake. In any case, thank your for the help!

D.

**Comment by ryanblock** [comment]
Hey @mrnagydavid, as described you are seeing expected behavior.

If Architect finds new resources that need to be provisioned in order to complete future deploys, it creates them during deployment. (This behavior came from consistent customer feedback.)

Arc intentionally does not have a concept of creating infra in only one environment or the other – this is deliberate so as to prevent environment drift and reduce bookkeeping about environment states.

Once your infra is created, `npx deploy` will deploy only to `staging`, and you should no longer see `Found new resources to create! Creating them now...` (until the next time you add new resources to your .arc manifest).

Hope that helps!

**Comment by mrnagydavid** [comment]
Thank you!

**Comment by brianleroux** [comment]
thx for asking! don't hesitate to ask more. we def can do a better job at documenting architect and this feedback super helps. 🙏
