### ISSUE TITLE
"get /" route shouldn't be required

### ISSUE THREAD

**Issue by roxeteer** [arc-repos/architect#345]
`@http` section shouldn't require the `get /` route when not building a website. My project is a set of Slack slash commands and none of them will be available on the root. Having a placeholder there is useless in this case.

**Comment by brianleroux** [comment]
ya it doesn't super have to be required…but felt like a good validation 

@ryanblock wdyt ?

**Comment by brianleroux** [comment]
ya it doesn't super have to be required…but felt like a good validation 

@ryanblock wdyt ?

**Comment by brianleroux** [comment]
Just reviewing and realized the reason we require the root is because we also use that lambda for 404 behavior. Otherwise there is no way to catch a missing route and API Gateway default is super confusing 403 error. This should be better documented (it's a recent addition). 

Still unsure if it's the right behavior. Ideally 'not found' is always handled but I'd understand if you don't care for an internal tool.

**Comment by roxeteer** [comment]
I've never used arc to build a website, only single-purpose Lambdas, so I really couldn't care less about 404s 😄

**Comment by ryanblock** [comment]
That's legit. If you only specify some combination of `@events`, `@indexes`, `@queues`, `@scheduled`, `@static`, `@tables`, etc., it would make sense that we wouldn't require you to opt into `@http`.

**Comment by brianleroux** [comment]
published in `@architect/architect@5.6.4`: thx!

**Comment by roxeteer** [comment]
My Lambdas are `@http` so apparently this means I still need `get /` after this change?

**Comment by brianleroux** [comment]
Nope.
